USE TennisChallenge
GO

CREATE TABLE TournamentMember(
TMemberId UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
MemberFk UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES Member(MemberKey),
TournamentFk UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES Tournaments(TournamentId)
ON UPDATE CASCADE
ON DELETE CASCADE,
TournamentPoints INT,
)