//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TennisWeb.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TennisWeb.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die E-Mail-Adresse oder das Passwort ist falsch..
        /// </summary>
        public static string AccountController_LogOn_The_user_name_or_password_provided_is_incorrect_ {
            get {
                return ResourceManager.GetString("AccountController_LogOn_The_user_name_or_password_provided_is_incorrect_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Werbemanager.
        /// </summary>
        public static string advertisementmanager {
            get {
                return ResourceManager.GetString("advertisementmanager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; muss zwischen {1:d} und {2:d} liegen..
        /// </summary>
        public static string BirthdayRange {
            get {
                return ResourceManager.GetString("BirthdayRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Zahl ist nicht korrekt..
        /// </summary>
        public static string CaptchaInvalid {
            get {
                return ResourceManager.GetString("CaptchaInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turnier Organisator.
        /// </summary>
        public static string casualtournamentorganizer {
            get {
                return ResourceManager.GetString("casualtournamentorganizer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Club Administrator.
        /// </summary>
        public static string clubadmin {
            get {
                return ResourceManager.GetString("clubadmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Manager.
        /// </summary>
        public static string eventmanager {
            get {
                return ResourceManager.GetString("eventmanager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feld bitte ausfüllen..
        /// </summary>
        public static string FieldRequired {
            get {
                return ResourceManager.GetString("FieldRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wirt.
        /// </summary>
        public static string host {
            get {
                return ResourceManager.GetString("host", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interclub Turnier Organisator.
        /// </summary>
        public static string intercluborganizer {
            get {
                return ResourceManager.GetString("intercluborganizer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ungültige E-Mail-Adresse.
        /// </summary>
        public static string InvalidEmailAddress {
            get {
                return ResourceManager.GetString("InvalidEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Platzwart.
        /// </summary>
        public static string janitor {
            get {
                return ResourceManager.GetString("janitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das {0} muss aus mindestens {2} Zeichen bestehen..
        /// </summary>
        public static string MinLengthPassword {
            get {
                return ResourceManager.GetString("MinLengthPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Passwörter stimmen nicht überein..
        /// </summary>
        public static string PasswordsDoNotMatch {
            get {
                return ResourceManager.GetString("PasswordsDoNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tennislehrer.
        /// </summary>
        public static string tennisteacher {
            get {
                return ResourceManager.GetString("tennisteacher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Newsmanager.
        /// </summary>
        public static string topicalitymanger {
            get {
                return ResourceManager.GetString("topicalitymanger", resourceCulture);
            }
        }
    }
}
